// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_clean_arch_template/test/data/repositories/repository_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_clean_arch_template/core/network/network_info.dart'
    as _i6;
import 'package:flutter_clean_arch_template/features/data/datasources/local_datasource/local_datasource.dart'
    as _i5;
import 'package:flutter_clean_arch_template/features/data/datasources/remote_datasource/remote_datasource.dart'
    as _i3;
import 'package:flutter_clean_arch_template/features/data/model/responses/drink_listing_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDrinkListingResponseModel_0 extends _i1.SmartFake
    implements _i2.DrinkListingResponseModel {
  _FakeDrinkListingResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDatasource extends _i1.Mock implements _i3.RemoteDatasource {
  MockRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DrinkListingResponseModel> searchDrink({
    required String? searchText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchDrink, [], {#searchText: searchText}),
            returnValue: _i4.Future<_i2.DrinkListingResponseModel>.value(
              _FakeDrinkListingResponseModel_0(
                this,
                Invocation.method(#searchDrink, [], {#searchText: searchText}),
              ),
            ),
          )
          as _i4.Future<_i2.DrinkListingResponseModel>);

  @override
  _i4.Future<_i2.DrinkListingResponseModel> getDrinkDetail({
    required String? drinkId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDrinkDetail, [], {#drinkId: drinkId}),
            returnValue: _i4.Future<_i2.DrinkListingResponseModel>.value(
              _FakeDrinkListingResponseModel_0(
                this,
                Invocation.method(#getDrinkDetail, [], {#drinkId: drinkId}),
              ),
            ),
          )
          as _i4.Future<_i2.DrinkListingResponseModel>);
}

/// A class which mocks [LocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDatasource extends _i1.Mock implements _i5.LocalDatasource {
  MockLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.DrinkModel> getListing() =>
      (super.noSuchMethod(
            Invocation.method(#getListing, []),
            returnValue: <_i2.DrinkModel>[],
          )
          as List<_i2.DrinkModel>);

  @override
  void saveListing(List<_i2.DrinkModel>? list) => super.noSuchMethod(
    Invocation.method(#saveListing, [list]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
